name: Auto build new list

on: 
  push:
    branches: 
      - dev
  schedule:
    - cron: "1 13 */6 * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run start.sh
      run: |
        ./start.sh
